# Generated by Django 4.1.3 on 2023-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='params',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
