# Generated by Django 4.1.3 on 2023-03-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_action_device_sensor_measure_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='device',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='source_label',
        ),
        migrations.AlterField(
            model_name='measure',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.sensor'),
        ),
    ]
