INTERACTION_REGISTER_DEVICE = 'CD'
INTERACTION_ASK_ACTION = 'AC'
INTERACTION_SAVE_MEASURE = 'SM'

INTERACTION_CHOICES = [
    (INTERACTION_REGISTER_DEVICE, 'Create Device'),
    (INTERACTION_ASK_ACTION, 'Ask Action'),
    (INTERACTION_SAVE_MEASURE, 'Save Measure'),
]
